# Generated by Django 3.1.1 on 2020-12-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('completed', models.BooleanField(default=False)),
                ('content', models.TextField(blank=True)),
                ('created', models.DateField(default='2020-12-11')),
                ('due_date', models.DateField(default='2020-12-11')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
