# Generated by Django 3.1.1 on 2021-01-09 01:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0008_auto_20201212_1252'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={},
        ),
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 1, 23, 21, 169268, tzinfo=utc)),
        ),
    ]
