# Generated by Django 3.1.1 on 2021-01-09 01:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoList', '0009_auto_20210108_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 1, 42, 45, 729664, tzinfo=utc)),
        ),
    ]
